### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by ronilbhatia** [ronilbhatia/EasyTrade#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the form adjusts properly (input boxes move up, sign in/sign up button moves down, and errors are displayed in between)
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
  - [x] Errors should display for both `/signup` and`/login`.
  - [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by xnanodax** [comment]
Great work and styling!!! This looks amazing, Ronil!

Just a few things to refine:

1) The `navbar` is just a little too wide compared to Robinhood!
![screen shot 2018-08-08 at 9 39 23 pm](https://user-images.githubusercontent.com/20424731/43878362-8e4fa9ea-9b53-11e8-8d08-b20db446d6b8.png)
![screen shot 2018-08-08 at 9 39 25 pm](https://user-images.githubusercontent.com/20424731/43878371-a3df87f8-9b53-11e8-840d-f0a5471f2c3c.png)


2) The picture to the right of the session form does not extend all the way down on my computer.
![screen shot 2018-08-08 at 9 34 15 pm](https://user-images.githubusercontent.com/20424731/43878331-5d1884d2-9b53-11e8-953a-820ad7a25065.png)
The white gap between the end of the session picture and this line is how much white space I saw on my browser.
